# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/surya-miuicamera/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),surya-miuicamera)

endif
